#########################################
# K suboru: proj2.c                     #
# Datum:    18.4.2024                   #
# Autor:    Martin Kovacik (xkovacm01)  #
# Projekt:  IOS project 2               #
#########################################


CC = gcc
CFLAGS =  -std=gnu99 -Wall -Wextra -Werror -pedantic -pthread
FILES = makefile proj2.c

all:	clean proj2

proj2:
	$(CC) $(CFLAGS) proj2.c -o proj2

clean:
	rm -rf proj2 proj2.out
